# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
  

  config.vm.hostname = "xdevel-deb-env"
  #config.vm.network "forwarded_port", guest: 80, host: 8080


  config.vm.provider "docker" do |d|
    d.build_dir = "."
    d.has_ssh = true

  end
  config.ssh.port = 22
  
end
